import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import { UserProvider } from "@/components/context";
import HeaderAdmins from "@/components/HeadersAdmins";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <HeaderAdmins />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
